### ISSUE TITLE
Add Autoplay next item option

### ISSUE THREAD

**Issue by shaunarundell** [MediaBrowser/MediaBrowser.Theater#117]
Automatically play the next item when the current is complete.

1. Next track for album
2. Next media item in view

essential for children shows
Should be implemented in tandem with the PlayNextTrack command

**Comment by thogil** [comment]
In v4, the play button for collections (e.g. series or seasons) queues all subsequent episodes automatically. We may still want to do this for times when the user plays just a single item.

**Comment by LukePulverenti** [comment]
Implemented in v4.
