### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by Ceten** [MediaBrowser/MediaBrowser.Theater#235]
When I try to log in to MBT with my user 'Cédric' I always get a login failure.

![screenshot 7](https://cloud.githubusercontent.com/assets/1673675/5505141/e26a6af2-878d-11e4-889e-19ae3e107448.png)

I did some testing and traced it down to the 'é' in my name. It seems MBT and the server can't handle logins with special characters. I did some digging in the code and solved it with html encoding/decoding.

It's really a simple change but I can do a pull request for both MediaBrowser.Theater and MediaBrowser.Server if you want.

**Comment by LukePulverenti** [comment]
Inapplicable now.
