### ISSUE TITLE
External player does not work in Windows 10 build 10074 x64 | internal 3D playback needed

### ISSUE THREAD

**Issue by HLFH** [MediaBrowser/MediaBrowser.Theater#240]
Hi,

Will MBT incorporate 3D playback for 3D MKV? The only 3D MKV (Half Top and Bottom, Half SBS) player that works is Cyberlink PowerDVD 15 Ultra. If MBT does not natively include 3D playback, it should add support to Cyberlink PowerDVD 15 Ultra as external player. In fact, I tested it as an external player: the program is launching but does not play any 3D MKV, we stay at the homepage of the PowerDVD software...

Thanks in advance,

**Comment by thogil** [comment]
It is possible that PowerDVD needs some custom setup for its arguments before it will play the file on start. You may get better luck asking about this on the [forum](http://emby.media/community/index.php?/forum/54-emby-theater/).

**Comment by HLFH** [comment]
Done here: http://emby.media/community/index.php?/topic/21448-cyberlink-powerdvd-ultra-15-as-an-external-player-need-help/

**Comment by HLFH** [comment]
@thogil Solved. I removed Emby server. I'm now using the "stack" [ownCloud](https://github.com/owncloud/core/) + [Embedded Videostream](https://apps.owncloud.com/content/show.php/Embedded+Videostream+++0.0.7?content=169002) + [PotPlayer](https://potplayer.daum.net/).
